apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niridoy/node-web-app.git
    targetRevision: deployment
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true