apiVersion: ap      containers:
      - name: node-web-app
        image: ghcr.io/niridoy/node-web-app@sha256:085c4862218d14bcc4b2772fa18361f053eeeab6
kind: Deployment
metadata:
  name: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: ghcr.io/niridoy/node-web-app@sha256:085c4862218d14bcc4b2772fa18361f053eeeab6
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-web-app
