apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk # base64 encoded "rootpassword"
  mysql-user: dXNlcg== # base64 encoded "user"
  mysql-password: cGFzc3dvcmQ= # base64 encoded "password"
